package com.lyh.blog.domain;
// Generated 2017-5-23 17:13:52 by Hibernate Tools 3.2.2.GA

/**
 * Admin generated by hbm2java
 */
public class Admin implements java.io.Serializable {

	private String password;
	private String username;

	public Admin() {
	}

	public Admin(String password, String username) {
		this.password = password;
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
