package com.lyh.blog.domain;
// Generated 2017-5-23 17:13:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer CId;
	private String name;
	private Date time;
	private Integer amount;

	public Category() {
	}

	public Category(String name, Date time,Integer amount) {
		this.name = name;
		this.time = time;
		this.amount=amount;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
