package com.lyh.blog.domain;
// Generated 2017-5-23 17:13:52 by Hibernate Tools 3.2.2.GA

/**
 * Myperofile generated by hbm2java
 */
public class Myprofile implements java.io.Serializable {

	private int UId;
	private String name;
	private Integer age;
	private String email;
	private String headUrl;
	private String weibo;
	private String qq;
	private String github;
	private String school;
	private String profile;
	private String web;
	private String ability;

	public Myprofile() {
	}

	public Myprofile(int UId) {
		this.UId = UId;
	}

	public Myprofile(int UId, String name, Integer age, String email, String headUrl, String weibo, String qq,
			String github, String school, String profile, String web, String ability) {
		this.UId = UId;
		this.name = name;
		this.age = age;
		this.email = email;
		this.headUrl = headUrl;
		this.weibo = weibo;
		this.qq = qq;
		this.github = github;
		this.school = school;
		this.profile = profile;
		this.web = web;
		this.ability = ability;
	}

	public int getUId() {
		return this.UId;
	}

	public void setUId(int UId) {
		this.UId = UId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getHeadUrl() {
		return this.headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	public String getWeibo() {
		return this.weibo;
	}

	public void setWeibo(String weibo) {
		this.weibo = weibo;
	}

	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	public String getGithub() {
		return this.github;
	}

	public void setGithub(String github) {
		this.github = github;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getProfile() {
		return this.profile;
	}

	public void setProfile(String profile) {
		this.profile = profile;
	}

	public String getWeb() {
		return this.web;
	}

	public void setWeb(String web) {
		this.web = web;
	}

	public String getAbility() {
		return this.ability;
	}

	public void setAbility(String ability) {
		this.ability = ability;
	}

}
