package com.lyh.blog.domain;
// Generated 2017-5-23 17:13:52 by Hibernate Tools 3.2.2.GA

/**
 * PageviewMonth generated by hbm2java
 */
public class PageviewMonth implements java.io.Serializable {

	private String month;
	private Integer amount;

	public PageviewMonth() {
	}

	public PageviewMonth(String month) {
		this.month = month;
	}

	public PageviewMonth(String month, Integer amount) {
		this.month = month;
		this.amount = amount;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
