package com.lyh.blog.domain;
// Generated 2017-5-23 17:13:52 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * PageviewDay generated by hbm2java
 */
public class PageviewDay implements java.io.Serializable {
	private String day;
	private Integer amount;

	public PageviewDay() {
	}

	



	public String getDay() {
		return day;
	}





	public void setDay(String day) {
		this.day = day;
	}





	public Integer getAmount() {
		return this.amount;
	}

	public void setAmount(Integer amount) {
		this.amount = amount;
	}

}
